### ISSUE TITLE
Email DataSource

### ISSUE THREAD

**Issue by Ameya-Pandya** [surakshashukla/Phishing-email-detection#1]
Hi,

Could you please tell from where did you get the email-data for analysis and is there any format of email do you require before parsing the data.

Thanks

**Comment by surakshashukla** [comment]
Hi,

I used data from enron email corpus. You can find it at www.enron-mail.com/email/<http://www.enron-mail.com/email/>.  The format I considered was also based on the data here. Hope it helps.

Thanks,
Suraksha

Sent from my iPhone

On Nov 29, 2017, at 8:20 AM, Ameya-Pandya <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Could you please tell from where did you get the email-data for analysis and is there any format of email do you require before parsing the data.

Thanks

**Comment by runchranda** [comment]
Hi, when I tried to run this program I got the error below:

Traceback (most recent call last):
  File "email_classification.py", line 26, in <module>
    spam = init_lists('linguistspam/spam/')
  File "email_classification.py", line 19, in init_lists
    file_list = os.listdir(folder)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'linguistspam/spam/'

Could you help me please?

**Comment by surakshashukla** [comment]
Hi, in that line code is expecting the files with the email data in the given path. Since you don't have the data there, you are getting "FileNotFoundError". I used Enron data, you can use the same. I hope this helps.

**Comment by runchranda** [comment]
Thank you for your respond. I have visited the link you provided for the Enron dataset but I see that there's a lot of directory and I'm not sure which one should I download or use. Also, if I may ask, did you convert all the data in one csv file?
